spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.0.101:3306/sec_kill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: pa55w0rd

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml